# Variables are inherited.
OPTIONS:
    cores: 5                                    # REQUIRED
    reference: "location/of/reference/ref.fa"
    analysis_dir: "testing"
    bam_dir: "bam"

#==============#
# Tool Options #
#==============#

# Only inherits options for commands
# located within the analysis config file.
COMMANDS:
    align:
        bwa:
            "__command__" : "mem" # Set as either mem, sampse, or sampe
        picard:
            markduplicates: True
        alignment_options:
            combine_like_samples: True
            remove_temp: True
    snps:
        samtools:
            "great" : "cool"
        freebayes:
            "greatNess" : "Cool"

    indels:
        samtools:
            "yes" : "yes"
        freebayes:
            "cool" : "great"

