# Variables are inherited.
OPTIONS:
    cores: 5                                            # REQUIRED
    fastq_dir: "FASTQ"
    reference: "WS245"
    analysis_dir: "testing"
    bam_dir: "bam"
    chrom_chunk_kb: 1000


