# Variables are inherited.
OPTIONS:
    DEBUG_workdir: "~/Documents/tmp/data"               # REQUIRED
    SLURM_workdir: "/lscr2/andersenlab/dec211/v2/DATA/" # REQUIRED
    cores: 5                                            # REQUIRED
    fastq_dir: "FASTQ"
    reference: "WS245"
    analysis_dir: "testing"
    bam_dir: "bam"

#==============#
# Tool Options #
#==============#

# Only inherits options for commands
# located within the analysis config file.
COMMANDS:
    align:
        bwa:
            "__command__" : "mem" # Set as either mem, sampse, or sampe
        picard:
            markduplicates: True
        alignment_options:
            remove_temp: True
    snps:
        samtools:
            "great" : "cool"
        freebayes:
            "greatNess" : "Cool"

    indels:
        samtools:
            "yes" : "yes"
        freebayes:
            "cool" : "great"

